Migrating data /Users/miko-work/Repos/genealogy-graph/parentage.csv using MM Engine localhost:4567 into graph mindmaps
match $p10 has identifier "Elizabeth Niesz"; $c0 has identifier "Mary Melissa Titus"; $p20 has identifier "William Sanford Titus";
insert isa parent-child (parent: $p10, child: $c0);
isa parent-child (parent: $p20, child: $c0);
match $p10 has identifier "Elizabeth Niesz"; $c0 has identifier "Barbara Ellen Titus"; $p20 has identifier "William Sanford Titus";
insert isa parent-child (parent: $p10, child: $c0);
isa parent-child (parent: $p20, child: $c0);
match $p10 has identifier "Elizabeth Niesz"; $c0 has identifier "Amanda Ann Titus"; $p20 has identifier "William Sanford Titus";
insert isa parent-child (parent: $p10, child: $c0);
isa parent-child (parent: $p20, child: $c0);
match $c0 has identifier "William Sanford Titus Jr."; $p10 has identifier "Elizabeth Niesz"; $p20 has identifier "William Sanford Titus";
insert isa parent-child (parent: $p10, child: $c0);
isa parent-child (parent: $p20, child: $c0);
match $p20 has identifier "Elizabeth Weaver"; $c0 has identifier "John Niesz"; $p10 has identifier "George Niesz";
insert isa parent-child (parent: $p10, child: $c0);
isa parent-child (parent: $p20, child: $c0);
match $p20 has identifier "Barbara Herchelroth"; $p10 has identifier "Jacob Young"; $c0 has identifier "Mary Young";
insert isa parent-child (parent: $p10, child: $c0);
isa parent-child (parent: $p20, child: $c0);
match $c0 has identifier "Elizabeth Niesz"; $p10 has identifier "John Niesz"; $p20 has identifier "Mary Young";
insert isa parent-child (parent: $p10, child: $c0);
isa parent-child (parent: $p20, child: $c0);
match $p10 has identifier "John Niesz"; $c0 has identifier "William Niesz"; $p20 has identifier "Mary Young";
insert isa parent-child (parent: $p10, child: $c0);
isa parent-child (parent: $p20, child: $c0);
match $c0 has identifier "Mary Niesz"; $p10 has identifier "John Niesz"; $p20 has identifier "Mary Young";
insert isa parent-child (parent: $p10, child: $c0);
isa parent-child (parent: $p20, child: $c0);
match $p10 has identifier "John Niesz"; $c0 has identifier "Jacob J. Niesz"; $p20 has identifier "Mary Young";
insert isa parent-child (parent: $p10, child: $c0);
isa parent-child (parent: $p20, child: $c0);
match $p10 has identifier "John Niesz"; $p20 has identifier "Mary Young"; $c0 has identifier "Catherine Niesz";
insert isa parent-child (parent: $p10, child: $c0);
isa parent-child (parent: $p20, child: $c0);
match $c0 has identifier "George W. Niesz"; $p10 has identifier "John Niesz"; $p20 has identifier "Mary Young";
insert isa parent-child (parent: $p10, child: $c0);
isa parent-child (parent: $p20, child: $c0);
match $c0 has identifier "Barbara Ellen Niesz"; $p10 has identifier "John Niesz"; $p20 has identifier "Mary Young";
insert isa parent-child (parent: $p10, child: $c0);
isa parent-child (parent: $p20, child: $c0);
match $p10 has identifier "John Niesz"; $p20 has identifier "Mary Young"; $c0 has identifier "John Kossuth Niesz";
insert isa parent-child (parent: $p10, child: $c0);
isa parent-child (parent: $p20, child: $c0);
match $p10 has identifier "John Niesz"; $c0 has identifier "Sarah Ann Niesz"; $p20 has identifier "Mary Young";
insert isa parent-child (parent: $p10, child: $c0);
isa parent-child (parent: $p20, child: $c0);
match $c0 has identifier "Benjamin Franklin Niesz"; $p10 has identifier "John Niesz"; $p20 has identifier "Mary Young";
insert isa parent-child (parent: $p10, child: $c0);
isa parent-child (parent: $p20, child: $c0);
match $p20 has identifier "Barbara Herchelroth"; $p10 has identifier "Jacob Young"; $c0 has identifier "Catherine Young";
insert isa parent-child (parent: $p10, child: $c0);
isa parent-child (parent: $p20, child: $c0);
match $p20 has identifier "Barbara Herchelroth"; $p10 has identifier "Jacob Young"; $c0 has identifier "Mary Young";
insert isa parent-child (parent: $p10, child: $c0);
isa parent-child (parent: $p20, child: $c0);
match $c0 has identifier "John Newman2"; $p10 has identifier "John Newman"; $p20 has identifier "Barbara Herchelroth";
insert isa parent-child (parent: $p10, child: $c0);
isa parent-child (parent: $p20, child: $c0);
match $p10 has identifier "John Newman"; $p20 has identifier "Barbara Herchelroth"; $c0 has identifier "Lawrence Newman";
insert isa parent-child (parent: $p10, child: $c0);
isa parent-child (parent: $p20, child: $c0);
match $p10 has identifier "John Newman"; $p20 has identifier "Barbara Herchelroth"; $c0 has identifier "Henry Newman";
insert isa parent-child (parent: $p10, child: $c0);
isa parent-child (parent: $p20, child: $c0);
match $p20 has identifier "Elizabeth"; $c0 has identifier "Margaret Newman"; $p10 has identifier "John Newman2";
insert isa parent-child (parent: $p10, child: $c0);
isa parent-child (parent: $p20, child: $c0);
match $p20 has identifier "Elizabeth"; $c0 has identifier "Haman Newman"; $p10 has identifier "John Newman2";
insert isa parent-child (parent: $p10, child: $c0);
isa parent-child (parent: $p20, child: $c0);
match $p20 has identifier "Elizabeth"; $c0 has identifier "Barbara Newman"; $p10 has identifier "John Newman2";
insert isa parent-child (parent: $p10, child: $c0);
isa parent-child (parent: $p20, child: $c0);
match $p20 has identifier "Elizabeth"; $c0 has identifier "Henry Newman2"; $p10 has identifier "John Newman2";
insert isa parent-child (parent: $p10, child: $c0);
isa parent-child (parent: $p20, child: $c0);
match $c0 has identifier "Barbara Newman2"; $p10 has identifier "Lawrence Newman"; $p20 has identifier "Isabelle McGaughey";
insert isa parent-child (parent: $p10, child: $c0);
isa parent-child (parent: $p20, child: $c0);
match $c0 has identifier "Lucinda Newman"; $p10 has identifier "Lawrence Newman"; $p20 has identifier "Isabelle McGaughey";
insert isa parent-child (parent: $p10, child: $c0);
isa parent-child (parent: $p20, child: $c0);
match $c0 has identifier "John Newman3"; $p10 has identifier "Lawrence Newman"; $p20 has identifier "Isabelle McGaughey";
insert isa parent-child (parent: $p10, child: $c0);
isa parent-child (parent: $p20, child: $c0);
match $p10 has identifier "Lawrence Newman"; $p20 has identifier "Isabelle McGaughey"; $c0 has identifier "Henry Newman3";
insert isa parent-child (parent: $p10, child: $c0);
isa parent-child (parent: $p20, child: $c0);
match $p10 has identifier "Lawrence Newman"; $c0 has identifier "Eliza Newman"; $p20 has identifier "Isabelle McGaughey";
insert isa parent-child (parent: $p10, child: $c0);
isa parent-child (parent: $p20, child: $c0);
match $c0 has identifier "John L. Newman"; $p20 has identifier "Sarah Hane"; $p10 has identifier "Henry Newman";
insert isa parent-child (parent: $p10, child: $c0);
isa parent-child (parent: $p20, child: $c0);
match $c0 has identifier "Barbara E. Newman"; $p20 has identifier "Sarah Hane"; $p10 has identifier "Henry Newman";
insert isa parent-child (parent: $p10, child: $c0);
isa parent-child (parent: $p20, child: $c0);
match $p20 has identifier "Sarah Hane"; $c0 has identifier "Amanda Newman"; $p10 has identifier "Henry Newman";
insert isa parent-child (parent: $p10, child: $c0);
isa parent-child (parent: $p20, child: $c0);
match $c0 has identifier "Catherine Newman"; $p20 has identifier "Sarah Hane"; $p10 has identifier "Henry Newman";
insert isa parent-child (parent: $p10, child: $c0);
isa parent-child (parent: $p20, child: $c0);
