Migrating data /Users/miko-work/Repos/genealogy-graph/people.csv using MM Engine localhost:4567 into graph mindmaps
insert $x0 isa person has identifier "Elizabeth Niesz" has name $name10;
$name10 value "Elizabeth" has order-number 1;
$gender0 has gender-type "female" isa gender;
isa genealogy-fact (fact-subject: $x0, known-fact: $gender0);
$x0 has family-name $surname0;
$surname0 has order-number 1 value "Niesz";
$birth0 has date "1820-08-27" isa birth;
isa genealogy-fact (fact-subject: $x0, known-fact: $birth0);
$death0 has date "1891-12-08" isa birth;
(fact-subject: $x0, known-fact: $death0) isa genealogy-fact;
insert $x0 has identifier "William Sanford Titus" isa person has name $name10;
$name10 has order-number 1 value "William";
$gender0 isa gender has gender-type "male";
isa genealogy-fact (fact-subject: $x0, known-fact: $gender0);
$x0 has family-name $surname0;
$surname0 has order-number 1 value "Titus";
$x0 has name $name20;
$name20 value "Sanford" has order-number 2;
$birth0 has date "1818-03-23" isa birth;
isa genealogy-fact (fact-subject: $x0, known-fact: $birth0);
$death0 isa birth has date "1905-01-01";
(fact-subject: $x0, known-fact: $death0) isa genealogy-fact;
insert $x0 isa person has identifier "Timothy Titus" has name $name10;
$name10 value "Timothy" has order-number 1;
$gender0 isa gender has gender-type "male";
isa genealogy-fact (fact-subject: $x0, known-fact: $gender0);
$x0 has family-name $surname0;
$surname0 has order-number 1 value "Titus";
insert $x0 isa person has identifier "Mary Guthrie" has name $name10;
$name10 has order-number 1 value "Mary";
$gender0 has gender-type "female" isa gender;
isa genealogy-fact (fact-subject: $x0, known-fact: $gender0);
$x0 has family-name $surname0;
$surname0 has order-number 1 value "Guthrie";
insert $x0 isa person has identifier "Mary Melissa Titus" has name $name10;
$name10 has order-number 1 value "Mary";
$gender0 has gender-type "female" isa gender;
isa genealogy-fact (fact-subject: $x0, known-fact: $gender0);
$x0 has family-name $surname0;
$surname0 has order-number 1 value "Titus";
$x0 has name $name20;
$name20 value "Melissa" has order-number 2;
$birth0 has date "1847-08-12" isa birth;
isa genealogy-fact (fact-subject: $x0, known-fact: $birth0);
$death0 has date "1946-05-10" isa birth;
(fact-subject: $x0, known-fact: $death0) isa genealogy-fact;
insert $x0 isa person has identifier "Barbara Ellen Titus" has name $name10;
$name10 value "Barbara" has order-number 1;
$gender0 has gender-type "female" isa gender;
isa genealogy-fact (fact-subject: $x0, known-fact: $gender0);
$x0 has family-name $surname0;
$surname0 has order-number 1 value "Titus";
$x0 has name $name20;
$name20 value "Ellen" has order-number 2;
$birth0 has date "1850-09-18" isa birth;
isa genealogy-fact (fact-subject: $x0, known-fact: $birth0);
$death0 isa birth has date "1933-01-10";
(fact-subject: $x0, known-fact: $death0) isa genealogy-fact;
insert $x0 has identifier "John Meyers" isa person has name $name10;
$name10 has order-number 1 value "John";
$gender0 isa gender has gender-type "male";
isa genealogy-fact (fact-subject: $x0, known-fact: $gender0);
$x0 has family-name $surname0;
$surname0 has order-number 1 value "Meyers";
insert $x0 isa person has identifier "Amanda Ann Titus" has name $name10;
$name10 has order-number 1 value "Amanda";
$gender0 has gender-type "female" isa gender;
isa genealogy-fact (fact-subject: $x0, known-fact: $gender0);
$x0 has family-name $surname0;
$surname0 has order-number 1 value "Titus";
$x0 has name $name20;
$name20 value "Ann" has order-number 2;
$birth0 has date "1845-09-10" isa birth;
isa genealogy-fact (fact-subject: $x0, known-fact: $birth0);
$death0 has date "1942-04-08" isa birth;
(fact-subject: $x0, known-fact: $death0) isa genealogy-fact;
insert $x0 isa person has identifier "Byron Culbertson" has name $name10;
$name10 value "Byron" has order-number 1;
$gender0 isa gender has gender-type "male";
isa genealogy-fact (fact-subject: $x0, known-fact: $gender0);
$x0 has family-name $surname0;
$surname0 value "Culbertson" has order-number 1;
insert $x0 isa person has name $name10 has identifier "William Sanford Titus Jr.";
$name10 has order-number 1 value "William";
$gender0 isa gender has gender-type "male";
isa genealogy-fact (fact-subject: $x0, known-fact: $gender0);
$x0 has family-name $surname0;
$surname0 has order-number 1 value "Titus";
$x0 has name $name20;
$name20 value "Sanford" has order-number 2;
$birth0 isa birth has date "1857-12-24";
isa genealogy-fact (fact-subject: $x0, known-fact: $birth0);
$death0 has date "1957-03-28" isa birth;
(fact-subject: $x0, known-fact: $death0) isa genealogy-fact;
insert $x0 isa person has identifier "Susan Josephine Dudley" has name $name10;
$name10 value "Susan" has order-number 1;
$gender0 has gender-type "female" isa gender;
isa genealogy-fact (fact-subject: $x0, known-fact: $gender0);
$x0 has family-name $surname0;
$surname0 value "Dudley" has order-number 1;
$x0 has name $name20;
$name20 has order-number 2 value "Josephine";
insert $x0 has identifier "John Niesz" isa person has name $name10;
$name10 has order-number 1 value "John";
$gender0 isa gender has gender-type "male";
isa genealogy-fact (fact-subject: $x0, known-fact: $gender0);
$x0 has family-name $surname0;
$surname0 has order-number 1 value "Niesz";
$birth0 isa birth has date "1798-01-02";
isa genealogy-fact (fact-subject: $x0, known-fact: $birth0);
$death0 has date "1872-03-06" isa birth;
(fact-subject: $x0, known-fact: $death0) isa genealogy-fact;
insert $x0 has identifier "George Niesz" isa person has name $name10;
$name10 value "George" has order-number 1;
$gender0 isa gender has gender-type "male";
isa genealogy-fact (fact-subject: $x0, known-fact: $gender0);
$x0 has family-name $surname0;
$surname0 has order-number 1 value "Niesz";
insert $x0 has identifier "Elizabeth Weaver" isa person has name $name10;
$name10 value "Elizabeth" has order-number 1;
$gender0 has gender-type "female" isa gender;
isa genealogy-fact (fact-subject: $x0, known-fact: $gender0);
$x0 has family-name $surname0;
$surname0 value "Weaver" has order-number 1;
insert $x0 has identifier "Mary Young" isa person has name $name10;
$name10 has order-number 1 value "Mary";
$gender0 has gender-type "female" isa gender;
isa genealogy-fact (fact-subject: $x0, known-fact: $gender0);
$x0 has family-name $surname0;
$surname0 value "Young" has order-number 1;
$birth0 isa birth has date "1798-04-09";
isa genealogy-fact (fact-subject: $x0, known-fact: $birth0);
$death0 has date "1868-10-28" isa birth;
(fact-subject: $x0, known-fact: $death0) isa genealogy-fact;
insert $x0 isa person has identifier "Jacob Young" has name $name10;
$name10 has order-number 1 value "Jacob";
$gender0 isa gender has gender-type "male";
isa genealogy-fact (fact-subject: $x0, known-fact: $gender0);
$x0 has family-name $surname0;
$surname0 value "Young" has order-number 1;
$death0 has date "before 1798-10" isa birth;
(fact-subject: $x0, known-fact: $death0) isa genealogy-fact;
insert $x0 isa person has identifier "Barbara Herchelroth" has name $name10;
$name10 value "Barbara" has order-number 1;
$gender0 has gender-type "female" isa gender;
isa genealogy-fact (fact-subject: $x0, known-fact: $gender0);
$x0 has family-name $surname0;
$surname0 value "Herchelroth" has order-number 1;
$birth0 has date "1773-06-06" isa birth;
isa genealogy-fact (fact-subject: $x0, known-fact: $birth0);
$death0 isa birth has date "1868-03-15";
(fact-subject: $x0, known-fact: $death0) isa genealogy-fact;
insert $x0 has identifier "John Newman" isa person has name $name10;
$name10 has order-number 1 value "John";
$gender0 isa gender has gender-type "male";
isa genealogy-fact (fact-subject: $x0, known-fact: $gender0);
$x0 has family-name $surname0;
$surname0 has order-number 1 value "Newman";
$birth0 isa birth has date "1774-08-02";
isa genealogy-fact (fact-subject: $x0, known-fact: $birth0);
$death0 has date "1862-12-26" isa birth;
(fact-subject: $x0, known-fact: $death0) isa genealogy-fact;
insert $x0 has identifier "William Niesz" isa person has name $name10;
$name10 has order-number 1 value "William";
$gender0 isa gender has gender-type "male";
isa genealogy-fact (fact-subject: $x0, known-fact: $gender0);
$x0 has family-name $surname0;
$surname0 has order-number 1 value "Niesz";
$birth0 isa birth has date "1822-05-28";
isa genealogy-fact (fact-subject: $x0, known-fact: $birth0);
$death0 isa birth has date "1913";
(fact-subject: $x0, known-fact: $death0) isa genealogy-fact;
insert $x0 isa person has identifier "Delilah Roush" has name $name10;
$name10 value "Delilah" has order-number 1;
$gender0 has gender-type "female" isa gender;
isa genealogy-fact (fact-subject: $x0, known-fact: $gender0);
$x0 has family-name $surname0;
$surname0 has order-number 1 value "Roush";
insert $x0 isa person has identifier "Ann Eliza Niesz" has name $name10;
$name10 value "Ann" has order-number 1;
$gender0 has gender-type "female" isa gender;
isa genealogy-fact (fact-subject: $x0, known-fact: $gender0);
$x0 has family-name $surname0;
$surname0 has order-number 1 value "Niesz";
$x0 has name $name20;
$name20 value "Eliza" has order-number 2;
insert $x0 isa person has name $name10 has identifier "Mary Niesz";
$name10 has order-number 1 value "Mary";
$gender0 has gender-type "female" isa gender;
isa genealogy-fact (fact-subject: $x0, known-fact: $gender0);
$x0 has family-name $surname0;
$surname0 has order-number 1 value "Niesz";
$birth0 has date "1824-05-29" isa birth;
isa genealogy-fact (fact-subject: $x0, known-fact: $birth0);
insert $x0 isa person has name $name10 has identifier "Samuel S. Bard";
$name10 value "Samuel" has order-number 1;
$gender0 isa gender has gender-type "male";
isa genealogy-fact (fact-subject: $x0, known-fact: $gender0);
$x0 has family-name $surname0;
$surname0 has order-number 1 value "Bard";
$x0 has name $name20;
$name20 has order-number 2 value "S.";
insert $x0 isa person has identifier "Jacob J. Niesz" has name $name10;
$name10 has order-number 1 value "Jacob";
$gender0 isa gender has gender-type "male";
isa genealogy-fact (fact-subject: $x0, known-fact: $gender0);
$x0 has family-name $surname0;
$surname0 has order-number 1 value "Niesz";
$x0 has name $name20;
$name20 value "J." has order-number 2;
$birth0 isa birth has date "1825-11-18";
isa genealogy-fact (fact-subject: $x0, known-fact: $birth0);
$death0 isa birth has date "1891-08";
(fact-subject: $x0, known-fact: $death0) isa genealogy-fact;
insert $x0 isa person has identifier "Catherine Niesz" has name $name10;
$name10 has order-number 1 value "Catherine";
$gender0 has gender-type "1827-10-20" isa gender;
isa genealogy-fact (fact-subject: $x0, known-fact: $gender0);
$x0 has family-name $surname0;
$surname0 has order-number 1 value "female";
$x0 has name $name20;
$name20 has order-number 2 value "Niesz";
insert $x0 isa person has name $name10 has identifier "George W. Niesz";
$name10 value "George" has order-number 1;
$gender0 isa gender has gender-type "male";
isa genealogy-fact (fact-subject: $x0, known-fact: $gender0);
$x0 has family-name $surname0;
$surname0 has order-number 1 value "Niesz";
$x0 has name $name20;
$name20 value "W." has order-number 2;
$birth0 isa birth has date "1829-09-12";
isa genealogy-fact (fact-subject: $x0, known-fact: $birth0);
$death0 isa birth has date "1904-03-26";
(fact-subject: $x0, known-fact: $death0) isa genealogy-fact;
insert $x0 isa person has identifier "Josephine" has name $name10;
$name10 has order-number 1 value "Josephine";
$gender0 has gender-type "female" isa gender;
isa genealogy-fact (fact-subject: $x0, known-fact: $gender0);
insert $x0 isa person has identifier "Barbara Ellen Niesz" has name $name10;
$name10 value "Barbara" has order-number 1;
$gender0 has gender-type "female" isa gender;
isa genealogy-fact (fact-subject: $x0, known-fact: $gender0);
$x0 has family-name $surname0;
$surname0 has order-number 1 value "Niesz";
$x0 has name $name20;
$name20 value "Ellen" has order-number 2;
$birth0 isa birth has date "1833-04-08";
isa genealogy-fact (fact-subject: $x0, known-fact: $birth0);
insert $x0 isa person has identifier "John Kossuth Niesz" has name $name10;
$name10 has order-number 1 value "John";
$gender0 isa gender has gender-type "male";
isa genealogy-fact (fact-subject: $x0, known-fact: $gender0);
$x0 has family-name $surname0;
$surname0 has order-number 1 value "Niesz";
$x0 has name $name20;
$name20 value "Kossuth" has order-number 2;
$birth0 has date "1836-11-22" isa birth;
isa genealogy-fact (fact-subject: $x0, known-fact: $birth0);
insert $x0 isa person has identifier "Maggie Billings" has name $name10;
$name10 has order-number 1 value "Maggie";
$gender0 has gender-type "female" isa gender;
isa genealogy-fact (fact-subject: $x0, known-fact: $gender0);
$x0 has family-name $surname0;
$surname0 value "Billings" has order-number 1;
insert $x0 isa person has name $name10 has identifier "Sarah Ann Niesz";
$name10 value "Sarah" has order-number 1;
$gender0 has gender-type "female" isa gender;
isa genealogy-fact (fact-subject: $x0, known-fact: $gender0);
$x0 has family-name $surname0;
$surname0 has order-number 1 value "Niesz";
$x0 has name $name20;
$name20 value "Ann" has order-number 2;
$birth0 isa birth has date "1840-01-19";
isa genealogy-fact (fact-subject: $x0, known-fact: $birth0);
insert $x0 isa person has identifier "Elam G. Smith" has name $name10;
$name10 value "Elam" has order-number 1;
$gender0 isa gender has gender-type "male";
isa genealogy-fact (fact-subject: $x0, known-fact: $gender0);
$x0 has family-name $surname0;
$surname0 has order-number 1 value "Smith";
$x0 has name $name20;
$name20 value "G." has order-number 2;
insert $x0 isa person has identifier "Benjamin Franklin Niesz" has name $name10;
$name10 has order-number 1 value "Benjamin";
$gender0 isa gender has gender-type "male";
isa genealogy-fact (fact-subject: $x0, known-fact: $gender0);
$x0 has family-name $surname0;
$surname0 has order-number 1 value "Niesz";
$x0 has name $name20;
$name20 value "Franklin" has order-number 2;
$birth0 has date "1842-11-16" isa birth;
isa genealogy-fact (fact-subject: $x0, known-fact: $birth0);
insert $x0 isa person has identifier "Rosalie" has name $name10;
$name10 value "Rosalie" has order-number 1;
$gender0 has gender-type "female" isa gender;
isa genealogy-fact (fact-subject: $x0, known-fact: $gender0);
insert $x0 isa person has identifier "Catherine Young" has name $name10;
$name10 has order-number 1 value "Catherine";
$gender0 has gender-type "female" isa gender;
isa genealogy-fact (fact-subject: $x0, known-fact: $gender0);
$x0 has family-name $surname0;
$surname0 value "Young" has order-number 1;
$birth0 has date "before 1798" isa birth;
isa genealogy-fact (fact-subject: $x0, known-fact: $birth0);
insert $x0 isa person has identifier "Frederick Shafner" has name $name10;
$name10 value "Frederick" has order-number 1;
$gender0 isa gender has gender-type "male";
isa genealogy-fact (fact-subject: $x0, known-fact: $gender0);
$x0 has family-name $surname0;
$surname0 value "Shafner" has order-number 1;
insert $x0 isa person has identifier "Andrew Shafner" has name $name10;
$name10 value "Andrew" has order-number 1;
$gender0 isa gender has gender-type "male";
isa genealogy-fact (fact-subject: $x0, known-fact: $gender0);
$x0 has family-name $surname0;
$surname0 value "Shafner" has order-number 1;
insert $x0 isa person has identifier "John Shafner" has name $name10;
$name10 has order-number 1 value "John";
$gender0 isa gender has gender-type "male";
isa genealogy-fact (fact-subject: $x0, known-fact: $gender0);
$x0 has family-name $surname0;
$surname0 value "Shafner" has order-number 1;
insert $x0 isa person has identifier "Elizabeth Shafner" has name $name10;
$name10 value "Elizabeth" has order-number 1;
$gender0 has gender-type "female" isa gender;
isa genealogy-fact (fact-subject: $x0, known-fact: $gender0);
$x0 has family-name $surname0;
$surname0 value "Shafner" has order-number 1;
insert $x0 isa person has name $name10 has identifier "Barbara Shafner";
$name10 value "Barbara" has order-number 1;
$gender0 has gender-type "female" isa gender;
isa genealogy-fact (fact-subject: $x0, known-fact: $gender0);
$x0 has family-name $surname0;
$surname0 value "Shafner" has order-number 1;
insert $x0 isa person has identifier "John Newman2" has name $name10;
$name10 has order-number 1 value "John";
$gender0 isa gender has gender-type "male";
isa genealogy-fact (fact-subject: $x0, known-fact: $gender0);
$x0 has family-name $surname0;
$surname0 has order-number 1 value "Newman";
$birth0 has date "circa 1803" isa birth;
isa genealogy-fact (fact-subject: $x0, known-fact: $birth0);
insert $x0 isa person has identifier "Elizabeth" has name $name10;
$name10 value "Elizabeth" has order-number 1;
$gender0 has gender-type "female" isa gender;
isa genealogy-fact (fact-subject: $x0, known-fact: $gender0);
insert $x0 isa person has identifier "Margaret Newman" has name $name10;
$name10 value "Margaret" has order-number 1;
$gender0 has gender-type "female" isa gender;
isa genealogy-fact (fact-subject: $x0, known-fact: $gender0);
$x0 has family-name $surname0;
$surname0 has order-number 1 value "Newman";
insert $x0 has identifier "Haman Newman" isa person has name $name10;
$name10 value "Haman" has order-number 1;
$gender0 isa gender has gender-type "male";
isa genealogy-fact (fact-subject: $x0, known-fact: $gender0);
$x0 has family-name $surname0;
$surname0 has order-number 1 value "Newman";
insert $x0 isa person has identifier "Barbara Newman" has name $name10;
$name10 value "Barbara" has order-number 1;
$gender0 has gender-type "female" isa gender;
isa genealogy-fact (fact-subject: $x0, known-fact: $gender0);
$x0 has family-name $surname0;
$surname0 has order-number 1 value "Newman";
insert $x0 isa person has identifier "Peter Newman" has name $name10;
$name10 has order-number 1 value "Peter";
$gender0 isa gender has gender-type "male";
isa genealogy-fact (fact-subject: $x0, known-fact: $gender0);
$x0 has family-name $surname0;
$surname0 has order-number 1 value "Newman";
insert $x0 isa person has name $name10 has identifier "Henry Newman2";
$name10 has order-number 1 value "Henry";
$gender0 isa gender has gender-type "male";
isa genealogy-fact (fact-subject: $x0, known-fact: $gender0);
$x0 has family-name $surname0;
$surname0 has order-number 1 value "Newman";
insert $x0 isa person has identifier "Lawrence Newman" has name $name10;
$name10 has order-number 1 value "Lawrence";
$gender0 isa gender has gender-type "male";
isa genealogy-fact (fact-subject: $x0, known-fact: $gender0);
$x0 has family-name $surname0;
$surname0 has order-number 1 value "Newman";
$birth0 has date "1804 circa" isa birth;
isa genealogy-fact (fact-subject: $x0, known-fact: $birth0);
insert $x0 isa person has name $name10 has identifier "Isabelle McGaughey";
$name10 value "Isabelle" has order-number 1;
$gender0 has gender-type "female" isa gender;
isa genealogy-fact (fact-subject: $x0, known-fact: $gender0);
$x0 has family-name $surname0;
$surname0 value "McGaughey" has order-number 1;
insert $x0 isa person has identifier "Barbara Newman2" has name $name10;
$name10 value "Barbara" has order-number 1;
$gender0 has gender-type "female" isa gender;
isa genealogy-fact (fact-subject: $x0, known-fact: $gender0);
$x0 has family-name $surname0;
$surname0 has order-number 1 value "Newman";
insert $x0 isa person has identifier "Lucinda Newman" has name $name10;
$name10 has order-number 1 value "Lucinda";
$gender0 has gender-type "female" isa gender;
isa genealogy-fact (fact-subject: $x0, known-fact: $gender0);
$x0 has family-name $surname0;
$surname0 has order-number 1 value "Newman";
insert $x0 isa person has identifier "John Newman3" has name $name10;
$name10 has order-number 1 value "John";
$gender0 isa gender has gender-type "male";
isa genealogy-fact (fact-subject: $x0, known-fact: $gender0);
$x0 has family-name $surname0;
$surname0 has order-number 1 value "Newman";
insert $x0 has identifier "Henry Newman3" isa person has name $name10;
$name10 has order-number 1 value "Henry";
$gender0 isa gender has gender-type "male";
isa genealogy-fact (fact-subject: $x0, known-fact: $gender0);
$x0 has family-name $surname0;
$surname0 has order-number 1 value "Newman";
insert $x0 has identifier "Eliza Newman" isa person has name $name10;
$name10 value "Eliza" has order-number 1;
$gender0 has gender-type "female" isa gender;
isa genealogy-fact (fact-subject: $x0, known-fact: $gender0);
$x0 has family-name $surname0;
$surname0 has order-number 1 value "Newman";
insert $x0 isa person has identifier "Henry Newman" has name $name10;
$name10 has order-number 1 value "Henry";
$gender0 isa gender has gender-type "male";
isa genealogy-fact (fact-subject: $x0, known-fact: $gender0);
$x0 has family-name $surname0;
$surname0 has order-number 1 value "Newman";
$birth0 isa birth has date "1811-03-06";
isa genealogy-fact (fact-subject: $x0, known-fact: $birth0);
$death0 isa birth has date "1898-09-10";
(fact-subject: $x0, known-fact: $death0) isa genealogy-fact;
insert $x0 has identifier "Sarah Hane" isa person has name $name10;
$name10 value "Sarah" has order-number 1;
$gender0 has gender-type "female" isa gender;
isa genealogy-fact (fact-subject: $x0, known-fact: $gender0);
$x0 has family-name $surname0;
$surname0 value "Hane" has order-number 1;
insert $x0 isa person has identifier "John L. Newman" has name $name10;
$name10 has order-number 1 value "John";
$gender0 isa gender has gender-type "male";
isa genealogy-fact (fact-subject: $x0, known-fact: $gender0);
$x0 has family-name $surname0;
$surname0 has order-number 1 value "Newman";
$x0 has name $name20;
$name20 value "L." has order-number 2;
insert $x0 has identifier "Barbara E. Newman" isa person has name $name10;
$name10 value "Barbara" has order-number 1;
$gender0 has gender-type "female" isa gender;
isa genealogy-fact (fact-subject: $x0, known-fact: $gender0);
$x0 has family-name $surname0;
$surname0 has order-number 1 value "Newman";
$x0 has name $name20;
$name20 has order-number 2 value "E.";
insert $x0 has identifier "Amanda Newman" isa person has name $name10;
$name10 has order-number 1 value "Amanda";
$gender0 has gender-type "female" isa gender;
isa genealogy-fact (fact-subject: $x0, known-fact: $gender0);
$x0 has family-name $surname0;
$surname0 has order-number 1 value "Newman";
insert $x0 isa person has identifier "Catherine Newman" has name $name10;
$name10 has order-number 1 value "Catherine";
$gender0 has gender-type "female" isa gender;
isa genealogy-fact (fact-subject: $x0, known-fact: $gender0);
$x0 has family-name $surname0;
$surname0 has order-number 1 value "Newman";
